version: '3.8'

services:
  app:
    build: .
    container_name: curacel-qa-service
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      ENV: dev
    restart: unless-stopped
